language: c

before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install gcc-arm-embedded

script:
  - make all

notifications:
  email: false

git:
  depth: 10
  
deploy:
  provider: releases
  api-key:
    secure: FJ1Ber0YA38hVvkhai+Dx3WjdEahaAv5kPm6XR6w56MzrC5OKlaGA/a9L13KD6GRmte5RI1CZw6aIM3SvwB9dFIjrv1tvgQNPGYv5lWr9WGPRloHxJq3ty/cGWs/0eoA60ZCeqhkMEX7XCiEYA1n1X7MR/Z/kBa1eaIDaOpb0iE=
  file: "build/T-962-controller.hex"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
